version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: ecommers-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI="mongodb://mongo:27017/ecommerse_api"
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: npm run dev

volumes:
  mongo-data: